GET https://remote-storage.developerakademie.org/item?key=users&token=BA5Q74H5JEV67SBOXGKABI20YCVNG0QK3KR6YEUI

//mit der VSC Erweiterung "REST Client" kannst du hier ansehen, was in der "Datenbank"hinterlegt ist